name: Build Spring Boot App and Deploy Docker Image to Linux

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

#      - name: Set up Maven
#        uses: s4u/setup-maven-action@v1.11.0
#        with:
#          maven-version: 3.9.9

      - name: Build Spring Boot App
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t droxy:latest .

      - name: Save Docker Image to File
        run: docker save droxy:latest | gzip > droxy.tar.gz

      - name: Copy Image to Remote Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "droxy.tar.gz"
          target: "/tmp"

      - name: Deploy on Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker load < /tmp/droxy.tar.gz
            docker stop droxy || true
            docker rm droxy || true
            docker run -d --name droxy -p 8080:8080 -v $HOME/droxy/h2:/data/h2 droxy:latest
